name: policies

on:
  create:

permissions:
  contents: read

jobs:
  policies:
    uses: mathewmusango/my-workflows/.github/workflows/branch-policy.yml@e2f8b4c80d81b452e8b19ed21e9b5ac62d94100c # v2026.0925.1503Z
