name: policies

on:
  create:

permissions:
  contents: read

jobs:
  policies:
    uses: mathewmusango/my-workflows/.github/workflows/branch-policy.yml@9216ec8c5a9090a380998275e7498422a02df9df # v2026.0925.1427Z
