name: Deploy

on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]

jobs:
  staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.head_branch == 'main' || startsWith(github.event.workflow_run.head_branch, 'v')) }}
    permissions:
      contents: read
      actions: read
      id-token: write
    uses: ./.github/workflows/deploy-staging.yml
    secrets:
      PROJECT: ${{ secrets.PROJECT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DEPLOY_ROLE_ARN: ${{ secrets.STAGING_DEPLOY_ROLE_ARN }}
      INVALIDATE_ROLE_ARN: ${{ secrets.STAGING_INVALIDATE_ROLE_ARN }}

  prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.head_branch == 'main' || startsWith(github.event.workflow_run.head_branch, 'v')) }}
    permissions:
      contents: read
      actions: read
      id-token: write
      pages: write
    uses: ./.github/workflows/deploy-prod.yml
    secrets:
      PROJECT: ${{ secrets.PROJECT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DEPLOY_ROLE_ARN: ${{ secrets.PROD_DEPLOY_ROLE_ARN }}
      INVALIDATE_ROLE_ARN: ${{ secrets.PROD_INVALIDATE_ROLE_ARN }}
