name: security

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  secrets:
    uses: mathewmusango/my-workflows/.github/workflows/security-gitleaks.yml@5a9c6ac6ab5285996efab6bef73a1b9c4978198d # v2026.1009.1321Z
  deps:
    uses: mathewmusango/my-workflows/.github/workflows/security-deps.yml@5a9c6ac6ab5285996efab6bef73a1b9c4978198d # v2026.1009.1321Z
  terraform:
    uses: mathewmusango/my-workflows/.github/workflows/security-terraform.yml@5a9c6ac6ab5285996efab6bef73a1b9c4978198d # v2026.1009.1321Z
